dcConsData = [
	{ "name": "에어케미.gif", "keywords": ["에어케미", "케미"], "tags": ["에어케미", "체퓨"] },
	{ "name": "에어케미2.gif", "keywords": ["에어케미2", "케미2"], "tags": ["에어케미", "체퓨"] },
	{ "name": "에어케미미소.gif", "keywords": ["에어케미3", "케미3", "케미미소"], "tags": ["에어케미", "체퓨"] },
	{ "name": "에어케미메롱.gif", "keywords": ["케미메롱"], "tags": ["에어케미", "체퓨"] },
	{ "name": "에어케미어라.gif", "keywords": ["케미어라", "케미이상", "케미궁금"], "tags": ["에어케미", "체퓨"] },
	{ "name": "에어케미띠용.gif", "keywords": ["케미띠용"], "tags": ["에어케미", "체퓨"] },
	{ "name": "에어케미눈물.gif", "keywords": ["케미슬픔", "케미눈물"], "tags": ["에어케미", "체퓨"] },
	{ "name": "에어케미애도.gif", "keywords": ["케미애도"], "tags": ["에어케미", "체퓨"] },
	{ "name": "에어케미경멸.gif", "keywords": ["케미경멸"], "tags": ["에어케미", "체퓨"] },
	{ "name": "에어케미액정.gif", "keywords": ["케미액정"], "tags": ["에어케미", "체퓨"] },
	{ "name": "에어케미아나.gif", "keywords": ["케미아나", "아나"], "tags": ["에어케미", "체퓨", "아나", "오버워치"] },
	{ "name": "에어케미고통.gif", "keywords": ["케미고통","다키스트"], "tags": ["에어케미", "체퓨","다키스트"] },
	{ "name": "에어케미콧바람.gif", "keywords": ["케미훗"], "tags": ["에어케미", "체퓨"] },
	{ "name": "에어케미시지.png", "keywords": ["케미시지"], "tags": ["에어케미", "체퓨", "시지"] },

	{ "name": "이프리트.gif", "keywords": ["이프리트"], "tags": ["이프리트", "파판"] },
	{ "name": "알렉스트라자.gif", "keywords": ["알렉스트라자", "알렉"], "tags": ["알렉스트라자", "알렉", "와우", "하스스톤"] },

	{ "name": "파돋이.gif", "keywords": ["파돋이", "해돋이"], "tags": ["파판"] },
	{ "name": "휴런핵박수만.gif", "keywords": ["휴런핵박수"], "tags": ["파판", "박수", "움짤"] },
	{ "name": "휴런핵정색.gif", "keywords": ["휴런핵정색"], "tags": ["파판", "움짤"] },
	{ "name": "휴런핵박수.gif", "keywords": ["휴런핵종합"], "tags": ["파판", "박수", "움짤"] },
	{ "name": "긴급조작.gif", "keywords": ["긴급조작"], "tags": ["파판"] },
	{ "name": "루이수아.gif", "keywords": ["루이수아", "희생", "전멸"], "tags": ["파판", "움짤"] },
	{ "name": "복권당첨.gif", "keywords": ["복권당첨"], "tags": ["파판"] },
	{ "name": "타마으쓱.gif", "keywords": ["타마으쓱", "으쓱"], "tags": ["파판", "움짤"] },

   	{ "name": "로터스말잇못.gif", "keywords": ["로터스말잇못", "로터스", "말잇못"], "tags": ["워프레임", "움짤"] },
	{ "name": "텐노핵박수.gif", "keywords": ["텐노핵박수","그리니어박수"], "tags": ["워프레임", "움짤"] },

	{ "name": "뮤트.gif", "keywords": ["뮤트", "재머"], "tags": ["시지", "움짤"] },
	{ "name": "알파팩.gif", "keywords": ["알파팩"], "tags": ["시지", "움짤"] },

	{ "name": "냥캣.gif", "keywords": ["냥캣"], "tags": ["고양이", "냥캣", "움짤"] },
   	{ "name": "amd.png", "keywords": ["amd", "암드"], "tags": ["암드", "투명"] },

	{ "name": "세야나.gif", "keywords": ["세야나"], "tags": ["아카네", "에어케미", "체퓨"] },
    { "name": "그렇구나.gif", "keywords": ["글쿠나", "그렇구나"], "tags": ["아카네", "에어케미", "체퓨"] },
    { "name": "와카루.gif", "keywords": ["와카루"], "tags": ["아카네", "에어케미", "체퓨"] },
    { "name": "알긋다.gif", "keywords": ["알긋다", "알겠다"], "tags": ["아카네", "에어케미", "체퓨"] },
	
	{ "name": "볼트고인.png", "keywords": ["볼트고인"], "tags": ["볼트"] },
	{ "name": "볼트공중.png", "keywords": ["볼트공중"], "tags": ["볼트"] },
	{ "name": "볼트구토.png", "keywords": ["볼트구토"], "tags": ["볼트"] },
	{ "name": "볼트넷여친.png", "keywords": ["볼트넷여친"], "tags": ["볼트"] },
	{ "name": "볼트넷친구.png", "keywords": ["볼트넷친구"], "tags": ["볼트"] },
	{ "name": "볼트딴딴.png", "keywords": ["볼트딴딴"], "tags": ["볼트"] },
	{ "name": "볼트루저.png", "keywords": ["볼트루저"], "tags": ["볼트"] },
	{ "name": "볼트몸상태.png", "keywords": ["볼트몸상태"], "tags": ["볼트"] },
	{ "name": "볼트미사일.png", "keywords": ["볼트미사일"], "tags": ["볼트"] },
	{ "name": "볼트민첩.png", "keywords": ["볼트민첩"], "tags": ["볼트"] },
	{ "name": "볼트부활.png", "keywords": ["볼트부활"], "tags": ["볼트"] },
	{ "name": "볼트빠따.png", "keywords": ["볼트빠따"], "tags": ["볼트"] },
	{ "name": "볼트수류탄.png", "keywords": ["볼트수류탄"], "tags": ["볼트"] },
	{ "name": "볼트신문.png", "keywords": ["볼트신문"], "tags": ["볼트"] },
	{ "name": "볼트심리.png", "keywords": ["볼트심리"], "tags": ["볼트"] },
	{ "name": "볼트에쎔.png", "keywords": ["볼트에쎔"], "tags": ["볼트"] },
	{ "name": "볼트연설.png", "keywords": ["볼트연설"], "tags": ["볼트"] },
	{ "name": "볼트우승.png", "keywords": ["볼트우승"], "tags": ["볼트"] },
	{ "name": "볼트자본.png", "keywords": ["볼트자본"], "tags": ["볼트"] },
	{ "name": "볼트자살.png", "keywords": ["볼트자살"], "tags": ["볼트"] },
	{ "name": "볼트장전.png", "keywords": ["볼트장전"], "tags": ["볼트"] },
	{ "name": "볼트저격.png", "keywords": ["볼트저격"], "tags": ["볼트"] },
	{ "name": "볼트전기톱.png", "keywords": ["볼트전기톱"], "tags": ["볼트"] },
	{ "name": "볼트토끼.png", "keywords": ["볼트토끼"], "tags": ["볼트"] },
	{ "name": "볼트파오후.png", "keywords": ["볼트파오후"], "tags": ["볼트"] },
	{ "name": "볼트펄럭.png", "keywords": ["볼트펄럭"], "tags": ["볼트"] },
	{ "name": "볼트화염병.png", "keywords": ["볼트화염병"], "tags": ["볼트"] },
	{ "name": "볼트활활.png", "keywords": ["볼트활활"], "tags": ["볼트"] },
	{ "name": "볼트활활2.png", "keywords": ["볼트활활2"], "tags": ["볼트"] }
	
	
];
